# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-23 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('style', models.CharField(max_length=10)),
                ('singer', models.CharField(max_length=20)),
                ('headerimg', models.FileField(upload_to='headerimg')),
                ('music', models.FileField(upload_to='music')),
            ],
            options={
                'db_table': 'musictable',
            },
        ),
    ]
